### ISSUE TITLE
Support of PHP 5.6?

### ISSUE THREAD

**Issue by sarfraznawaz2005** [nickkuijpers/laravel-custom-post-manager#9]
Any chance of adding PHP 5.6 support as it is still widely use ?

Thanks

**Comment by nickkuijpers** [comment]
Hi,

Do you know which issue occurs? It might be working in 5.6 already.

**Comment by sarfraznawaz2005** [comment]
composer doesn't install as you have version 7 specified in composer json file

**Comment by nickkuijpers** [comment]
Can you make a pull request? I will accept it.

**Comment by sarfraznawaz2005** [comment]
@nickkuijpers you just have to change php version from 7 to 5.6 in your package's composer file.

**Comment by nickkuijpers** [comment]
yes but im on the road atm, not at home. I be back this weekend, i will update it at that moment.

**Comment by nickkuijpers** [comment]
Hi @sarfraznawaz2005 

I've lowered the php requirement.
